[[pages]]
path = "Home.py"
name = "Home toml"
icon = ":house:"

[[pages]]
path = "pages/1_Forecast.py"
name = "Forecast toml"
icon = ":chart_with_upwards_trend:"

[[pages]]
path = "pages/2_Archive.py"
name = "Archive toml"
icon = ":books:"